# Generated by Django 4.2.7 on 2023-11-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='miqdor',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='narx',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
