# Generated by Django 4.2.7 on 2023-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='nasiya',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
